### PR TITLE
Added Support keyboard input for sample pictures app

### LINKED ISSUE #25: Support keyboard input for sample pictures app
To navigate to the next and previous pictures in the sample pictures app, allowing the user to press the arrow keys would make it convenient.

### PR DESCRIPTION
**Pull request by AkhileshMattam**
Closes #25 
Added a feature to navigate to the next and previous pictures in the sample pictures app, using left and right arrow key.

### CODE REVIEW

**Review by akshgpt7 — CHANGES_REQUESTED** [review]
Actually there's a small bug.
When we reach the last or first image, on pressing the arrow keys, the counter still increments, or decrements. You need to stop that when we reach the last or first image.
Also, please link the relevant issue in the PR description, so that it closes automatically when this is merged. ([Reference](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords))

**Comment by AkhileshMattam** [comment]
Closes #25 
Fixed the bug when we reach the last or first image, on pressing the arrow keys, the counter still increments, or decrements.

**Comment by akshgpt7** [comment]
@AkhileshMattam  Great! Just that you need to add the `closes #25` to the PR description (you added it to a new comment), it only works then. So, just edit the description (first comment in this thread, and add this).

**Comment by AkhileshMattam** [comment]
closes #25

**Comment by AkhileshMattam** [comment]
De

**Comment by akshgpt7** [comment]
Thanks, looks good!

**Pull request merged**
