### PR TITLE
Potential code refactor 

### PR DESCRIPTION
**Pull request by tusharnankani**
PR includes:

- Opening a file using with statement is preferred as function open implements the context manager protocol that releases the resource when it is outside of the with block. Not doing so requires you to manually release the resource.
- When comparing a variable to True, one should always use the form `if x is True` or simply `if x`. Since boolean in python are singletons, identity checks with `is` operator is recommended.

### CODE REVIEW

**Comment by akshgpt7** [comment]
Thanks for the PR @tusharnankani. The comparison with `True` changes are already handled in #37.
I agree that the `with` statement change is something we should keep, so I'll merge this once #37 is finalized and merged.

**Comment by akshgpt7** [comment]
@tusharnankani can you fix the merge conflicts before I merge these changes?

**Comment by tusharnankani** [comment]
> @tusharnankani can you fix the merge conflicts before I merge these changes?

Done @akshgpt7 👍🏻

**Comment by akshgpt7** [comment]
Looks good! Thanks for the PR.

**Pull request merged**
